### ISSUE TITLE
运行工程报错

### ISSUE THREAD

**Issue by liwei5544** [sansansisi/SSIDCard#2]
![wechatimg190](https://user-images.githubusercontent.com/25995237/40950886-2e05ddd6-68a7-11e8-9010-30e5c65beea7.jpeg)

**Comment by sansansisi** [comment]
你的xcode版本和手机系统版本方便告诉一下吗？

**Comment by sansansisi** [comment]
我知道你是怎么回事了，你应该是直接下载的zip解压运行的，这样会缺少opencv文件，你去https://github.com/opencv/opencv/releases 下载3.4.1版本的opencv2.framework替换掉本工程的opencv2.framework,然后执行pod install就可以正确执行示例程序。

**Comment by PamPanIOS** [comment]
ld: warning: ignoring file /Users/panyong/Downloads/SSIDCard-master/SSIDCard/Frameworks/opencv2.framework/opencv2, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/panyong/Downloads/SSIDCard-master/SSIDCard/Frameworks/opencv2.framework/opencv2
Undefined symbols for architecture arm64:

**Comment by PamPanIOS** [comment]
> 我知道你是怎么回事了，你应该是直接下载的zip解压运行的，这样会缺少opencv文件，你去https://github.com/opencv/opencv/releases 下载3.4.1版本的opencv2.framework替换掉本工程的opencv2.framework,然后执行pod install就可以正确执行示例程序。

按照你这么说的也报错误
