### ISSUE TITLE
ld: symbol(s) not found for architecture arm64  clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by MechanicalBrain** [sansansisi/SSIDCard#5]
ld: warning: ignoring file /Users/xxx/learngit/XXXXX/Pods/SSIDCard/SSIDCard/Frameworks/opencv2.framework/opencv2, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/xxx/learngit/XXXXX/Pods/SSIDCard/SSIDCard/Frameworks/opencv2.framework/opencv2 Undefined symbols for architecture arm64:   
"cv::Mat::copySize(cv::Mat const&)", referenced from:      
    cv::Mat::Mat(cv::Mat const&) in SSOpencvImageTool.o  
 "cv::Mat::create(int, int const*, int)", referenced from:       
    cv::Mat::create(int, int, int) in SSOpencvImageTool.o   
"cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)", referenced from:      
    cv::Mat::operator()(cv::Rect_<int> const&) const in SSOpencvImageTool.o   
"cv::fastFree(void*)", referenced from:       
    cv::Mat::operator=(cv::Mat&&) in SSOpencvImageTool.o       
    cv::Mat::~Mat() in SSOpencvImageTool.o   
"cv::boundingRect(cv::_InputArray const&)", referenced from:      
    -[SSOpencvImageTool ss_processImage:] in SSOpencvImageTool.o   
"cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)", referenced from:       
    adaptiveThereshold(cv::Mat) in SSOpencvImageTool.o  
 "cv::medianBlur(cv::_InputArray const&, cv::_OutputArray const&, int)", referenced from:      
    -[SSOpencvImageTool ss_processImage:] in SSOpencvImageTool.o   
"cv::findContours(cv::_InputOutputArray const&, cv::_OutputArray const&, int, int, cv::Point_<int>)", referenced from:       
   -[SSOpencvImageTool ss_processImage:] in SSOpencvImageTool.o   "cv::getStructuringElement(int, cv::Size_<int>, cv::Point_<int>)", referenced from:       
   -[SSOpencvImageTool ss_processImage:] in SSOpencvImageTool.o  
"cv::Mat::deallocate()", referenced from:       
   cv::Mat::release() in SSOpencvImageTool.o   
"cv::Mat::operator=(cv::Scalar_<double> const&)", referenced from:      
    -[SSOpencvImageTool matWithImage:] in SSOpencvImageTool.o   
"cv::erode(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::Point_<int>, int, int, cv::Scalar_<double> const&)", referenced from:       
   -[SSOpencvImageTool ss_processImage:] in SSOpencvImageTool.o 

ld: symbol(s) not found for architecture arm64 
clang: error: linker command failed with exit code 1 (use -v to see invocation)

大佬我pod安装后,编译,报这个错误,咋整啊?

https://www.extendi.it/blog/2015/5/22/46-how-to-add-opencv-2-4-11-in-your-ios-project
这个链接试过了,还是报错

**Comment by sansansisi** [comment]
请看主页怎么解决这个问题
